// DO NOT EDIT THIS FILE WITHOUT CONSULTING THE GROUP.
#ifndef _UNDERSEA_INVADERS_CONTROLLER_H
#define _UNDERSEA_INVADERS_CONTROLLER_H
#include "Model.h"
#include "View.h"

/*
  Manages player input and game output in an UnderSea Invaders game.
*/
class UnderSeaInvadersController(UnderSeaInvadersModel model) {
  public:
  UnderSeaInvadersController();
  ~UnderSeaInvadersController();
  // TODO (Checkpoint 2)

  private:
  // TODO (Checkpoint 2)
};

#endif